### ISSUE TITLE
Jenkins execution : Getting error WARN: Cannot read lintr_out.json file when trying to execute job using SonarScanner 

### ISSUE THREAD

**Issue by NLRKUM1** [Merck/sonar-r-plugin#11]
I have configured R sonar plugin in sonarqube server and installed R in my jenkins nodes.  But when tried to execute job from jenkins,  job got failed with error "WARN: Cannot read lintr_out.json file, skipping
java.nio.file.NoSuchFileException: lintr_out.json"

log :
NFO: Load project repositories (done) | time=420ms
INFO: 1456 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for r: Sonar way
INFO: ------------- Run sensors on module SonarTest
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=29ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=5ms
INFO: Sensor HTML [web]
INFO: Sensor HTML [web] (done) | time=21ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=10ms
INFO: Sensor LintR Sensor for R files [r]
INFO: Running sensor for LintR
WARN: Cannot read lintr_out.json file, skipping
java.nio.file.NoSuchFileException: lintr_out.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at com.msd.gin.common.sonar.LintRSensor.execute(LintRSensor.java:69)

**Comment by NLRKUM1** [comment]
Please let me know, how to fix this

**Comment by kmoco2am** [comment]
As described in the documentation, [you have to run LintR manually as part of your build process](https://github.com/Merck/sonar-r-plugin/blob/master/sample-project/README.md#run-lintr) to generate output in JSON format.

**Comment by NLRKUM1** [comment]
Thanks for your reply.

Getting below error. 
![image](https://user-images.githubusercontent.com/48484003/93067821-faf51f00-f67b-11ea-867a-2083cc7d174f.png)

**Comment by kmoco2am** [comment]
`run_lintr.R` is a sample script to demonstrate how you should run LintR for your project (it is just one line of R code to run LintR and put results into JSON file). It can be found here:
[https://github.com/Merck/sonar-r-plugin/blob/master/sample-project/run_lintr.R](https://github.com/Merck/sonar-r-plugin/blob/master/sample-project/run_lintr.R])
