### ISSUE TITLE
Exec format error 

### ISSUE THREAD

**Issue by narala558** [Merck/sonar-r-plugin#12]
Hi 
we tried to set up a sonar-r-plugin but we faced difficulty while setting up 

**Error**:  sonar-r-plugin/.sonar/sonarqube-7.9.1/bin/macosx-universal-64/./wrapper: Exec format error

Can you please help us here

**Comment by kmoco2am** [comment]
This seems like you are trying to run SonarQube server locally for debugging purposes. On which operating system? Could you just delete .sonar directory and retry if it helps?

**Comment by narala558** [comment]
Yes, I was trying to run sonarqube locally on ubuntu 18.04. 
And I also removed the .sonar directory still facing Exec format error occurs

Is there any particular OS need to follow?

**Comment by narala558** [comment]
I am able to solve this error 

But when I ran the sonar-scanner for the sample project only code files reflecting into sonarqube but not coverage, lines of code and all 

PFB screenshot

![image](https://user-images.githubusercontent.com/31549170/93167193-bb8f0700-f73d-11ea-8290-58a1d0570231.png)


Is there anything we need to change inside the plugin code?

**Comment by kmoco2am** [comment]
SonarQube is able to run on any major OSes (it is Java): Windows, Linux, MacOS. However, this is more a question to SonarQube itself. What was the issue that it searched for MacOS starter on Ubuntu? Some misconfiguration?

Currently, coverage is not supported. You should see number of bugs found on the files. Please check the JSON file generated by LintR if it contains information about found issues.

**Comment by narala558** [comment]
Yes In the script file by default it is taking mac OS changed to the respective OS

If coverage is not supported then even we will miss count for lines of code also right from the report

**Comment by narala558** [comment]
Code coverage is not supported it will be very useful if we integrate thiss
