### ISSUE TITLE
Is this plugin compatible with latest SonarQube LTS 8.9 ?

### ISSUE THREAD

**Issue by flzara** [Merck/sonar-r-plugin#14]
Is this plugin compatible with latest SonarQube LTS 8.9 ?
Thank you

**Comment by kmoco2am** [comment]
It should be. Did you find any issue using the plugin there?

**Comment by flzara** [comment]
Thx. So far no, but I'm just starting to test it. I wanted to make sure I'm not doing all this for nothing.
