### ISSUE TITLE
A couple of usage questions

### ISSUE THREAD

**Issue by kenahoo** [Merck/sonar-r-plugin#2]
Hi there, I'm interested in using `lintr` (or some other R code quality tool, but I don't know of any others) with Sonarqube, so your project looks intriguing.  A couple of questions:

1. `https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.7.4.zip` doesn't seem to be available anymore, the base URL has changed to `https://binaries.sonarsource.com`.  I also wanted to fetch a later version - would you recommend going with 6.7.6, or trying 7.5?  Same issue happens with 

2. I can't quite tell in the code where the `lintr_out.json` file is actually used.  If I want to change the name of that file, is there a config somewhere I'll need to change?

3. When I run the example commands in `sample-project/README.md`, it completes successfully but doesn't seem to actually upload any of the issues from `lintr_out.json`.  See screenshot.  Something wrong in my setup?

<img width="1015" alt="screen shot 2018-12-28 at 12 00 27 am" src="https://user-images.githubusercontent.com/111939/50526011-d9699380-0aa4-11e9-8b60-1adf4bcc8efa.png">

**Comment by kmoco2am** [comment]
Hi, first of all thanks for your pull request.

1.  I updated to the current LTS version and I update the links too (thank you again). I would recommend keep running with LTS if you need a sort of stability with your infrastructure.
2. Plugin has a configuration option to set which file is used as an lintr output. It is defined in `SonarRPlugin` class and it is called `sonar.r.lintr.output`. It can be added into your analysis configuration to change it (default is `lintr_out.json`)
3. It seems like that the plugin is not installed into SonarQube. You need to run `mvn verify` to copy plugin into local SonarQube instance. Check your administration page if the plugin is there.
