### ISSUE TITLE
Code line count

### ISSUE THREAD

**Issue by johanneswaage** [Merck/sonar-r-plugin#3]
Hello and thanks for providing this plugin.
I've managed to setup the plugin, and using `lintr` provides input for SQ, at least in the code smell category. However, there seems to be node line count of R code in SQ. Is this a limitation, or did I miss something?
Thanks

**Comment by kmoco2am** [comment]
I am glad to hear you made it working. Line count is a bit more complicated because it is dependent on proper R language parser implementation which is not there currently.

**Comment by kmoco2am** [comment]
I have merged the code provided in the pull request and slightly refactored. Please check and let me know. I would consider this to be done until we have full support for R languages somehow.
