### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by johanneswaage** [Merck/sonar-r-plugin#4]
Does the plugin sense and lint Rmarkdown files? (.Rmd)

**Comment by kmoco2am** [comment]
Currently no, it just takes output of LintR tool. Could you suggest how to lint Rmd files? Is LintR able to do that or is there any other tool for that? We are now working on adding test coverage reports.

**Comment by johanneswaage** [comment]
LintR has built-in support for rmd-files, but the `lintr::lint_package()` would skip these, as they're not part of a proper R package structure, so I digress.

Coverage from `covr` and tests from `testthat` would be awesome. `covr` exports to cobertura and `testhat` to junit, which SQ should support.

Thanks
