### ISSUE TITLE
Not able to find a InputFile with <pathtofile>/file.R

### ISSUE THREAD

**Issue by Not2Cre8ive** [Merck/sonar-r-plugin#6]
I have installed your plugin in SonarQube 7.9.2 and I am receiving the following error:  

> Not able to find a InputFile with /path/to/the/file.R

**Note: not the real path**

This error is repeated 19 times.
So in my logs, here's what I see:

> INFO: Sensor LintR Sensor for R files [r]
INFO: Running sensor for LintR
INFO: Issues found by LintR: 19
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
ERROR: Not able to find a InputFile with /path/to/the/file.R
INFO: Sensor LintR Sensor for R files [r] (done) | time=108ms 

It appears to me that the json file is being found and read to know that there are 19 issues, which is the correct number.  But when it tries to read the file.R itself, it can't seem to find/access it. 

The file.R exists in the same directory as the lintr_out.json.  Both files have the same permissions applied.  

Have you run across this issue before?  Please ask questions if you need more info.  I didn't want to provide too much unsolicited information.

**Comment by kmoco2am** [comment]
Hi, could you provide here the content of JSON file from LintR? Or some snippet? There should be found issues and the path to the file. The error message says that it cannot read the file by provided value from the JSON file.

**Comment by Not2Cre8ive** [comment]
Below is a snippet from the json file.  I, once again, changed the file path.  But the path in the real error message matches the error in the actual SonarQube log (triple checked that before posting).
 
```
  {
    "filename": "/path/to/the/file.R",
    "line_number": 1,
    "column_number": 5,
    "type": "style",
    "message": "Use <-, not =, for assignment.",
    "line": "fun = function(one)",
    "linter": "assignment_linter"
  },
  {
    "filename": "/path/to/the/file.R",
    "line_number": 2,
    "column_number": 1,
    "type": "style",
    "message": "Opening curly braces should never go on their own line and should always be followed by a new line.",
    "line": "{",
    "linter": "open_curly_linter"
  },
```

I even copy/pasted the path and did a cat command and that's how I got the above snippet.

**Comment by kmoco2am** [comment]
So lintr reports the issue on a file called /path/to/the/file.R but SonarQube scanner does not know this file. It is not in work directory. Please check that it exists.

**Comment by Not2Cre8ive** [comment]
The file exists.  I used the path generated in the json file to verify the file's existence. 
When you said "It is not in work directory", do you mean in SonarQube's work directory?

**Comment by Not2Cre8ive** [comment]
I will test on Monday, if not sooner, and get back to you.  Thanks!

**Comment by Not2Cre8ive** [comment]
I haven't forgot about getting back to you.  Still have not tested and will respond when I do.

**Comment by Not2Cre8ive** [comment]
Ok, sorry this has taken me so long to respond.  
When I change the path inside the .json file to make it relative, I don't get the error.
So it is something with the way I am executing the script to run my .R file thru the LintR tool.

I'll have to figure out how to generate the .json output and have it use the relative path.  

Thank you for your time!

**Comment by kmoco2am** [comment]
If I run sample in the project it uses full absolute paths and works normally. I am not sure how you generated JSON that uses absolute paths which actually do not exist. So relative or full absolute paths would be the fix for you.

**Comment by Not2Cre8ive** [comment]
I am using the example script found in your repo (sonar-r-plugin/sample-project/run_lintr.R).  It generate an absolute path that exists, so I'm confused as to why it doesn't work.  
The only other thing I can figure is that Jenkins is doing something that I'm not seeing just yet.  I'm trying to find cycles to investigate this further.
