### ISSUE TITLE
Missing linters

### ISSUE THREAD

**Issue by TheDurableDane** [Merck/sonar-r-plugin#8]
A lot of linters trigger errors in SonarQube, e.g. `seq_linter`.

Here are the linters that I had to remove (commented in the code) in order to make it work with the current plugin:
```
lint_dir(path = '.',
            linters = list(
                    # T_and_F_symbol_linter,  # yields SQ error
                    assignment_linter,
                    closed_curly_linter,
                    commas_linter,
                    commented_code_linter,
                    todo_comment_linter,
                    # cyclocomp_linter,  # yields SQ error
                    # object_name_linter,  # yields local error
                    object_length_linter,
                    camel_case_linter,
                    # equals_na_linter,  # yields SQ error
                    # extraction_operator_linter,  # yields SQ error
                    # function_left_parentheses_linter,  # yields SQ error
                    # implicit_integer_linter,  # yields SQ error
                    infix_spaces_linter,
                    line_length_linter,
                    no_tab_linter,
                    object_usage_linter,
                    open_curly_linter,
                    # paren_brace_linter,  # yields SQ error
                    absolute_path_linter,
                    nonportable_path_linter,
                    # pipe_continuation_linter,  # yields SQ error
                    semicolon_terminator_linter,
                    # seq_linter,  # yields SQ error
                    single_quotes_linter,
                    spaces_inside_linter,
                    spaces_left_parentheses_linter,
                    trailing_blank_lines_linter,
                    trailing_whitespace_linter,
                    undesirable_function_linter,
                    undesirable_operator_linter
                    # unneeded_concatenation_linter  # yields SQ error
    )
)
```

Have I done something wrong or are the linters not supported? If they are not supported, are there plans to support all the linters?

**Comment by Keith-Douglas** [comment]
This is distressing for those of us who would want to write more linters and use this plugin

**Comment by kmoco2am** [comment]
Rule definitions are hardcoded in the plugin because SonarQube, as far as I know, the rules are fixed and cannot be anyhow defined for each run separately. So adding new LintR rule means updating the plugin. I can definitely add the rules added into LintR tool.

**Comment by TheDurableDane** [comment]
@kmoco2am That would be really nice! Upgrading the plugin is no problem for me.

**Comment by kmoco2am** [comment]
Guys, could you provide a sample R code via PR which could be used for testing all the linters you are asking for?

**Comment by kmoco2am** [comment]
I have added all linters and updated a bit the code. Please look at it and let me know.

**Comment by TheDurableDane** [comment]
@kmoco2am Sorry for the delay. Looks good!
I see you have added some more "bad examples". Are you still in need of sample code?

**Comment by kmoco2am** [comment]
I am not sure I added samples to cover all linters. If you can add some more it would be great.

**Comment by TheDurableDane** [comment]
I'm not sure why, but I get permission denied when I try to push my changes to a new branch. Do you know why? (I'm new to contributing.)

**Comment by kmoco2am** [comment]
Please fork the repository and do whatever needed. Then you can open Pull Request into this original repository.
https://github.com/firstcontributions/first-contributions

**Comment by TheDurableDane** [comment]
I made a PR. Please let me know if it needs modifications.
Will Travis publish a new release once it is merged?

**Comment by kmoco2am** [comment]
PR is merged if I see it correctly. I can create new release if everything is fine.

**Comment by kmoco2am** [comment]
There is new version 0.2.1 which should be containing some fixes for linters above.
